package wow.character.service;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import wow.character.WowCharacterSpringTest;
import wow.commons.model.buffs.Buff;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * User: POlszewski
 * Date: 2022-11-19
 */
class SpellServiceTest extends WowCharacterSpringTest {
	@Autowired
	SpellService underTest;

	@Test
	void getAvailableSpells() {
		var spells = underTest.getAvailableSpells(getCharacter());

		assertThat(spells.stream().map(spell -> spell.getSpellId() + "#" + spell.getRank()).toList()).hasSameElementsAs(List.of(
				"Corruption#1",
				"Corruption#2",
				"Corruption#3",
				"Corruption#4",
				"Corruption#5",
				"Corruption#6",
				"Corruption#8",
				"Curse of Agony#1",
				"Curse of Agony#2",
				"Curse of Agony#3",
				"Curse of Agony#4",
				"Curse of Agony#5",
				"Curse of Agony#6",
				"Curse of Agony#7",
				"Curse of Doom#1",
				"Curse of Doom#2",
				"Death Coil#1",
				"Death Coil#2",
				"Death Coil#3",
				"Death Coil#4",
				"Drain Life#1",
				"Drain Life#2",
				"Drain Life#3",
				"Drain Life#4",
				"Drain Life#5",
				"Drain Life#6",
				"Drain Life#7",
				"Drain Life#8",
				"Life Tap#1",
				"Life Tap#2",
				"Life Tap#3",
				"Life Tap#4",
				"Life Tap#5",
				"Life Tap#6",
				"Life Tap#7",
				"Seed of Corruption#1",
				"Seed of Corruption (direct)#1",
				"Demon Armor#0",
				"Demonic Sacrifice#0",
				"Fel Armor#0",
				"Fel Domination#0",
				"Summon Imp#0",
				"Summon Voidwalker#0",
				"Summon Succubus#0",
				"Summon Felhunter#0",
				"Hellfire#1",
				"Hellfire#2",
				"Hellfire#3",
				"Hellfire#4",
				"Immolate#1",
				"Immolate#2",
				"Immolate#3",
				"Immolate#4",
				"Immolate#5",
				"Immolate#6",
				"Immolate#7",
				"Immolate#8",
				"Immolate#9",
				"Incinerate#1",
				"Incinerate#2",
				"Rain of Fire#1",
				"Rain of Fire#2",
				"Rain of Fire#3",
				"Rain of Fire#4",
				"Rain of Fire#5",
				"Searing Pain#1",
				"Searing Pain#2",
				"Searing Pain#3",
				"Searing Pain#4",
				"Searing Pain#5",
				"Searing Pain#6",
				"Searing Pain#7",
				"Searing Pain#8",
				"Shadow Bolt#1",
				"Shadow Bolt#2",
				"Shadow Bolt#3",
				"Shadow Bolt#4",
				"Shadow Bolt#5",
				"Shadow Bolt#6",
				"Shadow Bolt#7",
				"Shadow Bolt#8",
				"Shadow Bolt#9",
				"Shadow Bolt#10",
				"Shadow Bolt#11",
				"Shadowburn#1",
				"Shadowburn#2",
				"Shadowburn#3",
				"Shadowburn#4",
				"Shadowburn#5",
				"Shadowburn#6",
				"Shadowburn#7",
				"Shadowburn#8"
		));
	}

	@Test
	void getAvailableTalents() {
		var talents = underTest.getAvailableTalents(CHARACTER_CLASS, PHASE);

		assertThat(talents.stream().map(talent -> talent.getTalentId() + "#" + talent.getRank()).toList()).hasSameElementsAs(List.of(
				"Suppression#1",
				"Suppression#2",
				"Suppression#3",
				"Suppression#4",
				"Suppression#5",
				"Improved Corruption#1",
				"Improved Corruption#2",
				"Improved Corruption#3",
				"Improved Corruption#4",
				"Improved Corruption#5",
				"Improved Curse of Weakness#1",
				"Improved Curse of Weakness#2",
				"Improved Drain Soul#1",
				"Improved Drain Soul#2",
				"Improved Life Tap#1",
				"Improved Life Tap#2",
				"Soul Siphon#1",
				"Soul Siphon#2",
				"Improved Curse of Agony#1",
				"Improved Curse of Agony#2",
				"Fel Concentration#1",
				"Fel Concentration#2",
				"Fel Concentration#3",
				"Fel Concentration#4",
				"Fel Concentration#5",
				"Amplify Curse#1",
				"Grim Reach#1",
				"Grim Reach#2",
				"Nightfall#1",
				"Nightfall#2",
				"Empowered Corruption#1",
				"Empowered Corruption#2",
				"Empowered Corruption#3",
				"Shadow Embrace#1",
				"Shadow Embrace#2",
				"Shadow Embrace#3",
				"Shadow Embrace#4",
				"Shadow Embrace#5",
				"Siphon Life#1",
				"Curse of Exhaustion#1",
				"Shadow Mastery#1",
				"Shadow Mastery#2",
				"Shadow Mastery#3",
				"Shadow Mastery#4",
				"Shadow Mastery#5",
				"Contagion#1",
				"Contagion#2",
				"Contagion#3",
				"Contagion#4",
				"Contagion#5",
				"Dark Pact#1",
				"Improved Howl of Terror#1",
				"Improved Howl of Terror#2",
				"Malediction#1",
				"Malediction#2",
				"Malediction#3",
				"Unstable Affliction#1",
				"Improved Healthstone#1",
				"Improved Healthstone#2",
				"Improved Imp#1",
				"Improved Imp#2",
				"Improved Imp#3",
				"Demonic Embrace#1",
				"Demonic Embrace#2",
				"Demonic Embrace#3",
				"Demonic Embrace#4",
				"Demonic Embrace#5",
				"Improved Health Funnel#1",
				"Improved Health Funnel#2",
				"Improved Voidwalker#1",
				"Improved Voidwalker#2",
				"Improved Voidwalker#3",
				"Fel Intellect#1",
				"Fel Intellect#2",
				"Fel Intellect#3",
				"Improved Succubus#1",
				"Improved Succubus#2",
				"Improved Succubus#3",
				"Fel Domination#1",
				"Fel Stamina#1",
				"Fel Stamina#2",
				"Fel Stamina#3",
				"Demonic Aegis#1",
				"Demonic Aegis#2",
				"Demonic Aegis#3",
				"Master Summoner#1",
				"Master Summoner#2",
				"Unholy Power#1",
				"Unholy Power#2",
				"Unholy Power#3",
				"Unholy Power#4",
				"Unholy Power#5",
				"Improved Enslave Demon#1",
				"Improved Enslave Demon#2",
				"Demonic Sacrifice#1",
				"Master Conjuror#1",
				"Master Conjuror#2",
				"Mana Feed#1",
				"Mana Feed#2",
				"Mana Feed#3",
				"Master Demonologist#1",
				"Master Demonologist#2",
				"Master Demonologist#3",
				"Master Demonologist#4",
				"Master Demonologist#5",
				"Demonic Resilience#1",
				"Demonic Resilience#2",
				"Demonic Resilience#3",
				"Soul Link#1",
				"Demonic Knowledge#1",
				"Demonic Knowledge#2",
				"Demonic Knowledge#3",
				"Demonic Tactics#1",
				"Demonic Tactics#2",
				"Demonic Tactics#3",
				"Demonic Tactics#4",
				"Demonic Tactics#5",
				"Summon Felguard#1",
				"Improved Shadow Bolt#1",
				"Improved Shadow Bolt#2",
				"Improved Shadow Bolt#3",
				"Improved Shadow Bolt#4",
				"Improved Shadow Bolt#5",
				"Cataclysm#1",
				"Cataclysm#2",
				"Cataclysm#3",
				"Cataclysm#4",
				"Cataclysm#5",
				"Bane#1",
				"Bane#2",
				"Bane#3",
				"Bane#4",
				"Bane#5",
				"Aftermath#1",
				"Aftermath#2",
				"Aftermath#3",
				"Aftermath#4",
				"Aftermath#5",
				"Improved Firebolt#1",
				"Improved Firebolt#2",
				"Improved Lash of Pain#1",
				"Improved Lash of Pain#2",
				"Devastation#1",
				"Devastation#2",
				"Devastation#3",
				"Devastation#4",
				"Devastation#5",
				"Shadowburn#1",
				"Intensity#1",
				"Intensity#2",
				"Destructive Reach#1",
				"Destructive Reach#2",
				"Improved Searing Pain#1",
				"Improved Searing Pain#2",
				"Improved Searing Pain#3",
				"Pyroclasm#1",
				"Pyroclasm#2",
				"Improved Immolate#1",
				"Improved Immolate#2",
				"Improved Immolate#3",
				"Improved Immolate#4",
				"Improved Immolate#5",
				"Ruin#1",
				"Nether Protection#1",
				"Nether Protection#2",
				"Nether Protection#3",
				"Emberstorm#1",
				"Emberstorm#2",
				"Emberstorm#3",
				"Emberstorm#4",
				"Emberstorm#5",
				"Backlash#1",
				"Backlash#2",
				"Backlash#3",
				"Conflagrate#1",
				"Soul Leech#1",
				"Soul Leech#2",
				"Soul Leech#3",
				"Shadow and Flame#1",
				"Shadow and Flame#2",
				"Shadow and Flame#3",
				"Shadow and Flame#4",
				"Shadow and Flame#5",
				"Shadowfury#1"
		));
	}

	@Test
	void getAvailableBuffs() {
		List<Buff> buffs = underTest.getBuffs(getCharacter());

		List<String> names = buffs.stream().map(Buff::getName).toList();

		assertThat(names).hasSameElementsAs(List.of(
				"Arcane Brilliance",
				"Prayer of Fortitude",
				"Prayer of Spirit",
				"Gift of the Wild",
				"Greater Blessing of Kings",
				"Fel Armor",
				"Touch of Shadow",
				"Burning Wish",
				"Brilliant Wizard Oil",
				"Superior Wizard Oil",
				"Well Fed (sp)",
				"Flask of Supreme Power",
				"Flask of Pure Death",
				"Moonkin Aura",
				"Wrath of Air Totem",
				"Totem of Wrath",
				"Misery",
				"Shadow Weaving",
				"Improved Scorch",
				"Curse of the Elements",
				"Curse of the Elements (improved)",
				"Drums of Battle",
				"Destruction"
		));
	}
}