services:
    mongodb:
        image: mongodb/mongodb-community-server:6.0-ubi8
        environment:
            - MONGODB_INITDB_ROOT_USERNAME=user
            - MONGODB_INITDB_ROOT_PASSWORD=pass
        ports:
            - 27017:27017
        volumes:
            - ../data:/data/db
        networks:
            - internalnet
        restart: unless-stopped
    backend-minmax:
        container_name: wow-minmax-container
        build:
            context: .
            dockerfile: services/wow-minmax/Dockerfile
        image: wow-minmax
        ports:
            - 8080:8080
        expose:
            - 8080
        networks:
            - internalnet
        restart: unless-stopped
        depends_on:
            - mongodb
            - backend-simulator
    backend-simulator:
        container_name: wow-simulator-container
        build:
            context: .
            dockerfile: services/wow-simulator/Dockerfile
        image: wow-simulator
        ports:
            - 8090:8090
        expose:
            - 8090
        networks:
            - internalnet
        restart: unless-stopped
    frontend:
        container_name: wow-minmax-ui-container
        build: apps/wow-minmax-ui
        image: wow-minmax-ui
        ports:
            - 80:80
        expose:
            - 80
        networks:
            - internalnet
        restart: unless-stopped
        depends_on:
            - backend-minmax

networks:
    internalnet:
        driver: bridge
