services:
    mongodb:
        image: mongodb/mongodb-community-server:6.0-ubi8
        environment:
            - MONGODB_INITDB_ROOT_USERNAME=user
            - MONGODB_INITDB_ROOT_PASSWORD=pass
        ports:
            - 27017:27017
        volumes:
            - ../data:/data/db
        networks:
            - internalnet
        restart: unless-stopped
    backend:
        container_name: wow-minmax_container
        build:
            context: .
            dockerfile: services/wow-minmax/Dockerfile
        image: wow-minmax
        ports:
            - 8080:8080
        expose:
            - 8080
        networks:
            - internalnet
        restart: unless-stopped
        depends_on:
            - mongodb
    frontend:
        container_name: wow-minmax-ui_container
        build: apps/wow-minmax-ui
        image: wow-minmax-ui
        ports:
            - 80:80
        expose:
            - 80
        networks:
            - internalnet
        restart: unless-stopped
        depends_on:
            - backend

networks:
    internalnet:
        driver: bridge
