export enum PhaseId {
	VANILLA_P1 = 'VANILLA_P1',
	VANILLA_P2 = 'VANILLA_P2',
	VANILLA_P2_5 = 'VANILLA_P2_5',
	VANILLA_P3 = 'VANILLA_P3',
	VANILLA_P4 = 'VANILLA_P4',
	VANILLA_P5 = 'VANILLA_P5',
	VANILLA_P6 = 'VANILLA_P6',
	
	TBC_P0 = 'TBC_P0',
	TBC_P1 = 'TBC_P1',
	TBC_P2 = 'TBC_P2',
	TBC_P3 = 'TBC_P3',
	TBC_P4 = 'TBC_P4',
	TBC_P5 = 'TBC_P5',
	
	WOTLK_P0 = 'WOTLK_P0',
	WOTLK_P1 = 'WOTLK_P1',
}
