export enum Profession {
	ENCHANTING = 'ENCHANTING',
	JEWELCRAFTING = 'JEWELCRAFTING',
	INSCRIPTION = 'INSCRIPTION',
	ALCHEMY = 'ALCHEMY',
	TAILORING = 'TAILORING',
	LEATHERWORKING = 'LEATHERWORKING',
	BLACKSMITHING = 'BLACKSMITHING',
	ENGINEERING = 'ENGINEERING',
	HERBALISM = 'HERBALISM',
	MINING = 'MINING',
	SKINNING = 'SKINNING',
}
