export enum ItemSubType {
	DAGGER = 'DAGGER',
	SWORD = 'SWORD',
	AXE = 'AXE',
	POLEARM = 'POLEARM',
	MACE = 'MACE',
	STAFF = 'STAFF',
	FIST_WEAPON = 'FIST_WEAPON',

	HELD_IN_OFF_HAND = 'HELD_IN_OFF_HAND',
	SHIELD = 'SHIELD',

	WAND = 'WAND',
	GUN = 'GUN',
	BOW = 'BOW',
	CROSSBOW = 'CROSSBOW',
	THROWN = 'THROWN',

	TOTEM = 'TOTEM',
	LIBRAM = 'LIBRAM',
	IDOL = 'IDOL',

	CLOTH = 'CLOTH',
	LEATHER = 'LEATHER',
	MAIL = 'MAIL',
	PLATE = 'PLATE',
}
