base.stat.infos.xls.file.path=/wow/character/data/base-stat-infos.xls
character.templates.xls.file.path=/wow/character/data/character-templates.xls
gear.sets.xls.file.path=/wow/character/data/gear-sets.xls
assets.xls.file.path=/wow/character/data/assets.xls
