export enum CharacterClass {
	MAGE = 'MAGE',
	WARLOCK = 'WARLOCK',
	PRIEST = 'PRIEST',
	DRUID = 'DRUID',
	ROGUE = 'ROGUE',
	HUNTER = 'HUNTER',
	SHAMAN = 'SHAMAN',
	PALADIN = 'PALADIN',
	WARRIOR = 'WARRIOR',
}
