export enum Race {
	UNDEAD = 'UNDEAD',
	ORC = 'ORC',
	TROLL = 'TROLL',
	TAUREN = 'TAUREN',
	BLOOD_ELF = 'BLOOD_ELF',
	HUMAN = 'HUMAN',
	DWARF = 'DWARF',
	GNOME = 'GNOME',
	NIGHT_ELF = 'NIGHT_ELF',
	DRANEI = 'DRANEI',
}
