
buff.items.by.slot={\
    'NECK':{\
        'Braided Eternium Chain',\
        'Chain of the Twilight Owl',\
        'Embrace of the Dawn',\
        'Eye of the Night',\
        'Living Ruby Pendant',\
        'Thick Felsteel Necklace'\
    }\
}