server.port=8080

upgrades.api.url=http://localhost:8085/api/v1/upgrades
stats.api.url=http://localhost:8085/api/v1/stats
simulator.api.url=http://localhost:8090/api/v1/simulations

spring.autoconfigure.exclude= \
  org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, \
  org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

wow.minmax.file.repo.directory=../wow-minmax-data